name: Payload

on:
  workflow_dispatch:
  
jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Check Out
      uses: actions/checkout@v4

    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@main

    - name: Prepare the environment
      run: |
        sudo apt update
        sudo apt -y install python3 python3.12-venv python3-pip
      continue-on-error: true
      
    - name: Setup Env
      run: |
        python3 -m venv teknologia
        source teknologia/bin/activate
      continue-on-error: true
    
    - name: Setup Payload Dumper
      run: |
        pip install git+https://github.com/5ec1cff/payload-dumper
        wget -O payload.bin https://filebin.net/5k6cbzl2hnmg6a71/payload.bin
      continue-on-error: true     

    - name: Dumper
      run: |
        payload_dumper --partitions boot,system payload.bin
      continue-on-error: true
